export { default as HomePage         } from './Home'
export { default as AboutPage        } from './About'
export { default as IntroPage        } from './Intro'
export { default as InsiderPage      } from './Insider'
export { default as ContactPage      } from './Contact'
export { default as NewsPage         } from './News'
export { default as NewsDetail       } from './News/NewsDetail'
export { default as Login            } from './Auth/Login'
export { default as LoginPassword    } from './Auth/Login/LoginPassword'
export { default as Register         } from './Auth/Register'
export { default as RegisterPassword } from './Auth/Register/RegisterPassword'
export { default as RegisterUserDetails  } from './Auth/Register/RegisterUserDetails'
// export { default as ForgotPassword } from "./Auth/ForgotPassword";
